
/* MAIN */

const SYMBOL_ERROR = '✖';
const SYMBOL_FOCUSED = '❯';
const SYMBOL_INFO = 'ℹ';
const SYMBOL_QUESTION = '?';
const SYMBOL_SELECTED = '●';
const SYMBOL_SUCCESS = '✔';
const SYMBOL_UNSELECTED = '○';
const SYMBOL_WARNING = '!';

/* EXPORT */

export {SYMBOL_ERROR, SYMBOL_FOCUSED, SYMBOL_INFO, SYMBOL_QUESTION, SYMBOL_SELECTED, SYMBOL_SUCCESS, SYMBOL_UNSELECTED, SYMBOL_WARNING};
